name: CI Pipeline for Spark Processor

    # This workflow runs on every push to the main branch
on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]

jobs:
  build-and-test:
        # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

          # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

          # Step 3: Install Java (required by Spark)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

          # Step 4: Install dependencies from our requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r spark_processor/requirements.txt

          # Step 5: Run the tests with pytest
      - name: Run Pytest
        run: |
          pytest spark_processor/test_processor.py